export const DEFAULT_URL = "https://cors-sherry.herokuapp.com/https://api.yelp.com/v3/businesses/search"
//export const API_KEY = "5X38boeUrnJ5FkVVqFxgSz8IhvkVx5xVRlvZU4Iu-k6Cras83bjnJgK5Vo0owGpIgP0CzXHmyXonGGRwy8-580n5U7DrTFh4ng0LCLDVSjb3C3741k8oiL8fIjy8X3Yx"
export const RESTAURANT_URL = "https://cors-sherry.herokuapp.com/https://api.yelp.com/v3/businesses"
export const API_KEY = "FaK5uFWq7WXCt79ebCf-TUIiYID_j6oWtxEMvTwP-efpOH_ZXl6D9VYRLsnrAcZe0qyvvZX06VajIirLmzCANj866ch0O2h4Dk9m7kYDJLF-UQeIyoQfsMsWpI_BX3Yx"
export const MAP_URL = "https://api.zippopotam.us/us"
export const REVIEW_URL = "https://web-project-server.herokuapp.com/api/reviews"
export const USER_URL = "https://web-project-server.herokuapp.com/api/users"
